# Generated by Django 4.1 on 2022-09-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
