# Generated by Django 4.1 on 2022-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_myuser_is_admin_alter_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_premium',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
