# Generated by Django 4.1 on 2022-09-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_myuser_is_premium_alter_myuser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumUser',
        ),
    ]
