# Generated by Django 4.1 on 2022-09-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_delete_premiumuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='mybook',
        ),
    ]
