# Generated by Django 4.1 on 2022-09-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(null=True, upload_to='filamoon/'),
        ),
    ]
