# Generated by Django 4.1 on 2022-09-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontent', '0003_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
